version: "3.3"
services:
  web:
    image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: local_web
    env_file: ./.env.php
    ports:
      - 8080:80
  db:
    image: mysql:8.0.26
    volumes:
      - ./:/home
    container_name: local_db
    env_file: ./.env.mysql
